[package]
name = "Proof-Hour"
version = "0.1"
lean_version = "leanprover-community/lean:3.51.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "5d0c76894ada7940957143163d7b921345474cbc"}
